In [3]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))

120


In [4]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [5]:
def test():
    print("test() for function")
    return
test()


test() for function


In [6]:
class Demo1:
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact * n
            n = n-1
        return fact
p1=Demo1()
p1.fact(5)

120

In [7]:
class Person(object):
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())


Anil False


In [9]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

b=np.array([[10,20,30],[40,50,60]])
c=np.array(a+b)
print(c)
c.reshape(3,2)

[[11 22 33]
 [44 55 66]]


array([[11, 22],
       [33, 44],
       [55, 66]])

In [12]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,10])
print(np.diagonal((a1,a2,a3)))
print(np.trace((a1,a2,a3)))

[ 1  5 10]
16


In [15]:
import numpy as np
np.arange(1,100,9)



array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [16]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [17]:
np.arange(1,2048,564)
np.arange(1,20,5)



array([ 1,  6, 11, 16])

In [18]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])




slicing column : [2 5]


In [19]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,2])

slicing column : [3 6]


In [20]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])


first row : [1 2 3]


In [21]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])


second row : [4 5 6]


In [22]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)


[[1 2 3]
 [4 5 6]]


In [23]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median Value=",np.median(a1))

[3.33884843 4.66009334 2.9015794  5.08908185 6.86823753 4.54481647
 4.91933962 5.30130177 4.0196736  3.97078826]
Min value= 2.901579402802051
Max value= 6.868237528190794
Mean value= 4.561376028508866
Median Value= 4.6024549072896175


In [25]:
a1=np.array(([1,2],[3,4]))
a2=np.array(([5,6],[6,7]))
print(np.dot(a1,a2))

[[17 20]
 [39 46]]


In [3]:
import pandas as pd
dict={"Name":["Chiikar","Surya","Mohit","Guddu"],
      "Email ID":["chiikar@mabbu.com","Surya@Great.com","Mohit@gangleader.com","Guddu@sate.com"],
      "Mobile Number":["12345678910","1235467098","6543217890","3467853643"],
      "Address":["Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

      Name              Email ID Mobile Number Address
0  Chiikar     chiikar@mabbu.com   12345678910     Hyd
1    Surya       Surya@Great.com    1235467098     Hyd
2    Mohit  Mohit@gangleader.com    6543217890     Hyd
3    Guddu        Guddu@sate.com    3467853643     Hyd
